Neos:
  Flow:
    mvc:
      routes:
        'NeosRulez.Shop.Payment': true
  Neos:
    nodeTypes:
      groups:
        payment:
          position: 'end'
          label: 'Payment'
    fusion:
      autoInclude:
        NeosRulez.Shop.Payment: true

NeosRulez:
  Shop:
    Payment:
      payments:
        -
          nodeType: 'NeosRulez.Shop.Payment:Payment.Prepayment'
          class: 'NeosRulez\Shop\Payment\Prepayment'
